In [41]:
pip install notebook

Note: you may need to restart the kernel to use updated packages.


In [42]:

import numpy as np
l = (3, 3)
O = np.ones(l)
R = np.random.random(l)
Z = np.zeros(l)
C = np.arange(l[0])
print(f"Віднімання:\n {C - (O + 10)}")
print(f"Множення:\n {O * R}")
print(f"Ділення:\n {R / C}")
print(f"Степінь:\n {C ** Z}")
print(f"Порівняння:\n {R > 0.5}")
print(f"Ділення на 0:\n {O / Z}")


Віднімання:
 [[-11. -10.  -9.]
 [-11. -10.  -9.]
 [-11. -10.  -9.]]
Множення:
 [[0.068053   0.28751045 0.95295312]
 [0.47431148 0.91666441 0.63850905]
 [0.50429798 0.32741125 0.48393795]]
Ділення:
 [[       inf 0.28751045 0.47647656]
 [       inf 0.91666441 0.31925452]
 [       inf 0.32741125 0.24196897]]
Степінь:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Порівняння:
 [[False False  True]
 [False  True  True]
 [ True False False]]
Ділення на 0:
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


C:\Users\User\AppData\Local\Temp\ipykernel_22720\2384104627.py:9: RuntimeWarning: divide by zero encountered in divide
  print(f"Ділення:\n {R / C}")
C:\Users\User\AppData\Local\Temp\ipykernel_22720\2384104627.py:12: RuntimeWarning: divide by zero encountered in divide
  print(f"Ділення на 0:\n {O / Z}")


In [43]:

eye_matrix = np.eye(3)
comparison = eye_matrix == 1
print(f"Матриця одиничних елементів:\n{eye_matrix}")
print(f"Порівняння на наявність одиничних елементів:\n{comparison}")
ones_matrix = np.ones((3, 3))
result = ones_matrix - eye_matrix
print(f"Результат віднімання:\n{result}")

Матриця одиничних елементів:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Порівняння на наявність одиничних елементів:
[[ True False False]
 [False  True False]
 [False False  True]]
Результат віднімання:
[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]


In [44]:

A = np.array([[1, 2, 3], [2, 2, 2], [3, 3, 3]])
B = np.array([[3, 2, 1], [1, 2, 3], [-1, -2, -3]])

print(f"Маємо два масиви:\n {A} \n {B}")
R = A * B
print(f"Поелементне множення:\n {R}")
R = np.dot(A, B)
print(f"Множення як матриць:\n {R}")
MA = np.mat(A)
MB = np.mat(B)
R = MA * MB
print(f"Перетворення на матриці і множення:\n {R}")


Маємо два масиви:
 [[1 2 3]
 [2 2 2]
 [3 3 3]] 
 [[ 3  2  1]
 [ 1  2  3]
 [-1 -2 -3]]
Поелементне множення:
 [[ 3  4  3]
 [ 2  4  6]
 [-3 -6 -9]]
Множення як матриць:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]
Перетворення на матриці і множення:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]


In [45]:
A = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
B = np.array([1, 2, 3])
C = B[:, np.newaxis]
print(f"Вектор B є рядком: {B.shape} {B}")
print(f"Вектор C є стовпцем: {C.shape} {C}")
print(f"Додавання по рядках:\n {A + B}")
print(f"Додавання по стовпцям:\n {A + C}")

Вектор B є рядком: (3,) [1 2 3]
Вектор C є стовпцем: (3, 1) [[1]
 [2]
 [3]]
Додавання по рядках:
 [[12 14 16]
 [22 24 26]
 [32 34 36]]
Додавання по стовпцям:
 [[12 13 14]
 [23 24 25]
 [34 35 36]]


In [46]:
D = np.ones(3)
Z = np.zeros((3, 1))

print(f"Конкатенація рядків: {np.concatenate((D, D))}")
print(f"Конкатенація стовпців:\n {np.concatenate((Z, Z))}")
print(f"Конкатенація з D:\n {np.concatenate((B, D))}")
print(f"Конкатенація з C з reshape:\n {np.concatenate((C, D.reshape((3,1))))}")

# Повторення
print(f"Повторення масиву: {np.tile(D, (2, 3))}")


Конкатенація рядків: [1. 1. 1. 1. 1. 1.]
Конкатенація стовпців:
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Конкатенація з D:
 [1. 2. 3. 1. 1. 1.]
Конкатенація з C з reshape:
 [[1.]
 [2.]
 [3.]
 [1.]
 [1.]
 [1.]]
Повторення масиву: [[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [47]:
O = np.arange(6).reshape(3, 2)
O_r = O.reshape((2, 3))
O_f = O.flatten()
O_t = O.transpose()
O_fl = np.flip(O)
O_fa = np.flip(O, axis=1)

print(f"Оригінальний масив:\n{O}")
print(f"Перетворений на іншу форму:\n{O_r}")
print(f"Масив у вигляді рядка:\n{O_f}")
print(f"Транспонований масив:\n{O_t}")
print(f"Перевернутий масив:\n{O_fl}")
print(f"Перевернуті стовпці:\n{O_fa}")


Оригінальний масив:
[[0 1]
 [2 3]
 [4 5]]
Перетворений на іншу форму:
[[0 1 2]
 [3 4 5]]
Масив у вигляді рядка:
[0 1 2 3 4 5]
Транспонований масив:
[[0 2 4]
 [1 3 5]]
Перевернутий масив:
[[5 4]
 [3 2]
 [1 0]]
Перевернуті стовпці:
[[1 0]
 [3 2]
 [5 4]]


In [48]:
# 1. Створіть вектор з 12 елементів
vector = np.arange(12)
print(f"Вектор з 12 елементів:\n {vector}")

# 2. Змініть розмірність перетворивши вектор у матрицю
matrix = vector.reshape(3, 4)
print(f"Масив з вектора:\n {matrix}")

# 3. Транспонування
transposed_matrix = matrix.T
print(f"Транспоновану матрицю:\n {transposed_matrix}")

# 4. Перевернути матрицю
reversed_matrix = np.flip(matrix, axis=1)
print(f"Перевернута матриця:\n {reversed_matrix}")

# 5. Перетворіть багатовимірний масив на вектор
flattened_matrix = matrix.flatten()
print(f"Перетворена матриця на вектор:\n {flattened_matrix}")


Вектор з 12 елементів:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Масив з вектора:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Транспоновану матрицю:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Перевернута матриця:
 [[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]
Перетворена матриця на вектор:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
